"""
ZT-ATE Glass-Box Evaluator — Gemini Pro Report Synthesis
=========================================================
Wraps ReportService with a Gemini Pro layer that replaces the deterministic
`consensus_summary` with a deep, neuro-symbolic narrative.

Trigger contract
────────────────
`GlassBoxEvaluator.synthesize()` is the single call-site for Glass-Box report
generation. It is triggered exclusively by:
  - Session finalization  (`finalize_session` in orchestrator.py)
  - Operator-initiated report pull (`build_glass_box_report` in orchestrator.py)

EEOC Boundary
─────────────
The Gemini Pro prompt INCLUDES the telemetry overlay *summary* (aggregate counts,
latest stress index, overlay_lag_ms) because the Glass-Box report is an
OPERATOR-ONLY artifact. The Pro model is explicitly instructed that biometric
signals played ZERO role in the technical verdict. The `candidate_safe_summary`
is generated by the deterministic path and sanitized through GuardrailService —
it never passes through Gemini Pro.

Graceful Degradation
────────────────────
If the Pro API call fails (rate limit, safety block, timeout, import error),
`synthesize()` returns the deterministic base report unchanged. The interview
outcome is never blocked by an LLM availability issue.
"""

from __future__ import annotations

import asyncio
import json
import logging
from typing import TYPE_CHECKING

from app.contracts import (
    GlassBoxReport,
    HumanReviewRecord,
    InterviewSessionSnapshot,
    TraceEvent,
)

if TYPE_CHECKING:
    from app.services.reporting import ReportService

_log = logging.getLogger(__name__)

# Hard ceiling: Pro calls are expensive; the report pipeline cannot wait forever.
_PRO_SYNTHESIS_TIMEOUT = 45.0  # seconds

# ---------------------------------------------------------------------------
# Prompt template
# ---------------------------------------------------------------------------

_GLASS_BOX_PROMPT = """You are a senior technical interview evaluator producing a Glass-Box audit report.

## Interview Summary
- Candidate Role: {candidate_role}
- Session ID: {session_id}
- Technical Score: {technical_score:.1f} / 100
- Recommendation: {recommendation}
- Verdict Locked: {verdict_locked}
- Contamination Check Passed: {contamination_check}

## Task Outcomes
{task_outcomes_block}

## Rubric Scores
{rubric_scores_block}

## Evidence Artifacts
{evidence_block}

## Operator Telemetry Overlay (aggregate — excluded from scoring)
- Overlay Enabled: {overlay_enabled}
- Total Biometric Points: {overlay_points}
- Total Stress Segments: {overlay_segments}
- Latest Stress Index: {latest_stress}
- Latest Heart Rate BPM: {latest_bpm}
- Overlay Processing Lag: {overlay_lag}ms
- Excluded from Automated Scoring: YES (EEOC-compliant)

## Operator Review Flags
{review_flags_block}

## Reasoning Trace Depth
- Total Trace Events: {trace_count}

---

Generate a **Neuro-Symbolic Glass-Box Consensus Summary** for this interview session.

Requirements:
1. Synthesize the technical performance narrative in 3-5 paragraphs.
2. Reference specific task outcomes and rubric scores by name.
3. Acknowledge the operator telemetry overlay as contextual, non-scoring data.
4. State explicitly that biometric signals DID NOT influence the technical verdict.
5. Provide a final hiring signal (Advance / Hold / Reject) with a brief rationale.
6. Use clear, professional language suitable for a hiring committee.
7. Do NOT invent data not present in the summary above.

Output ONLY the Markdown report body (no JSON, no code fences, no preamble)."""


# ---------------------------------------------------------------------------
# Helper: build prompt sections
# ---------------------------------------------------------------------------


def _fmt_task_outcomes(snapshot: InterviewSessionSnapshot) -> str:
    lines = []
    for task in snapshot.technical.task_outcomes:
        duration_s = round(task.duration_ms / 1000, 1)
        lines.append(
            f"- **{task.title}** | status={task.status} | "
            f"failed_actions={task.failed_action_count} | duration={duration_s}s\n"
            f"  {task.summary}"
        )
    return "\n".join(lines) if lines else "(no task outcomes recorded)"


def _fmt_rubric_scores(snapshot: InterviewSessionSnapshot) -> str:
    lines = []
    for rs in snapshot.technical.rubric_scores:
        pct = round((rs.score / rs.max_score) * 100, 1) if rs.max_score else 0
        lines.append(
            f"- **{rs.label}**: {rs.score:.1f}/{rs.max_score:.1f} ({pct}%) — {rs.rationale}"
        )
    return "\n".join(lines) if lines else "(no rubric scores recorded)"


def _fmt_evidence(snapshot: InterviewSessionSnapshot) -> str:
    lines = []
    for artifact in snapshot.technical.evidence_bundle:
        lines.append(f"- [{artifact.artifact_type}] {artifact.label}")
    return "\n".join(lines) if lines else "(no evidence artifacts)"


def _fmt_review_flags(snapshot: InterviewSessionSnapshot) -> str:
    flags = list(snapshot.overlay.operator_review_flags)
    for seg in snapshot.overlay.review_segments:
        flags.append(
            f"[{seg.priority.upper()}] stress_delta={seg.stress_delta:+.2f} "
            f"confidence={seg.confidence:.2f} — {seg.review_rationale}"
        )
    return "\n".join(f"- {f}" for f in flags) if flags else "(no operator flags)"


def _build_prompt(
    snapshot: InterviewSessionSnapshot,
    traces: list[TraceEvent],
) -> str:
    verdict = snapshot.technical.technical_verdict
    overlay = snapshot.overlay

    latest_stress = (
        f"{overlay.latest_stress_index:.2f}" if overlay.latest_stress_index is not None else "N/A"
    )
    latest_bpm = str(overlay.latest_heart_rate_bpm) if overlay.latest_heart_rate_bpm else "N/A"

    return _GLASS_BOX_PROMPT.format(
        candidate_role=snapshot.candidate_role,
        session_id=snapshot.session_id,
        technical_score=snapshot.technical.technical_score,
        recommendation=verdict.recommendation if verdict else "pending",
        verdict_locked=verdict.locked if verdict else False,
        contamination_check=verdict.contamination_check_passed if verdict else True,
        task_outcomes_block=_fmt_task_outcomes(snapshot),
        rubric_scores_block=_fmt_rubric_scores(snapshot),
        evidence_block=_fmt_evidence(snapshot),
        overlay_enabled=overlay.overlay_enabled,
        overlay_points=len(overlay.telemetry_timeline),
        overlay_segments=len(overlay.stress_markers),
        latest_stress=latest_stress,
        latest_bpm=latest_bpm,
        overlay_lag=overlay.overlay_processing_lag_ms,
        review_flags_block=_fmt_review_flags(snapshot),
        trace_count=len(traces),
    )


# ---------------------------------------------------------------------------
# GlassBoxEvaluator
# ---------------------------------------------------------------------------


class GlassBoxEvaluator:
    """
    Gemini Pro wrapper around ReportService.

    Usage (in orchestrator.py):
        evaluator = GlassBoxEvaluator(report_service=self.report_service)
        report = await evaluator.synthesize(snapshot=snapshot, traces=traces, ...)
    """

    def __init__(self, report_service: ReportService) -> None:
        self.report_service = report_service

    async def synthesize(
        self,
        snapshot: InterviewSessionSnapshot,
        traces: list[TraceEvent],
        summary_note: str | None = None,
        latest_review: HumanReviewRecord | None = None,
    ) -> GlassBoxReport:
        """
        Build the Glass-Box report.

        Always produces a valid report. Gemini Pro enriches `consensus_summary`;
        on any failure the deterministic base summary is preserved.
        """
        # Step 1: deterministic base — always succeeds, never touches LLM
        base_report = await self.report_service.build_report(
            snapshot=snapshot,
            traces=traces,
            summary_note=summary_note,
            latest_review=latest_review,
        )

        # Step 2: Gemini Pro enrichment — best-effort
        pro_summary = await self._call_gemini_pro(snapshot, traces)

        if pro_summary:
            _log.info(
                "Gemini Pro Glass-Box synthesis succeeded. session_id=%s chars=%d",
                snapshot.session_id,
                len(pro_summary),
            )
            return base_report.model_copy(update={"consensus_summary": pro_summary})

        _log.info(
            "Using deterministic consensus_summary (Pro unavailable). session_id=%s",
            snapshot.session_id,
        )
        return base_report

    async def build_report(
        self,
        snapshot: InterviewSessionSnapshot,
        traces: list[TraceEvent],
        summary_note: str | None = None,
        latest_review: HumanReviewRecord | None = None,
    ) -> GlassBoxReport:
        """
        Duck-type alias for ReportService.build_report().
        Allows GlassBoxEvaluator to be passed wherever ReportService is expected.
        """
        return await self.synthesize(
            snapshot=snapshot,
            traces=traces,
            summary_note=summary_note,
            latest_review=latest_review,
        )

    async def _call_gemini_pro(
        self,
        snapshot: InterviewSessionSnapshot,
        traces: list[TraceEvent],
    ) -> str | None:
        """
        Call Gemini Pro to synthesize the neuro-symbolic consensus narrative.
        Returns None on any failure — caller falls back to deterministic summary.
        """
        try:
            from app.services.genai_config import get_pro_model
        except ImportError:
            _log.error("google-generativeai not installed — skipping Pro synthesis.")
            return None

        prompt = _build_prompt(snapshot, traces)

        try:
            model = get_pro_model()
            response = await asyncio.wait_for(
                model.generate_content_async(prompt),
                timeout=_PRO_SYNTHESIS_TIMEOUT,
            )
            text: str = response.text.strip()
            if not text:
                _log.warning(
                    "Gemini Pro returned empty response. session_id=%s", snapshot.session_id
                )
                return None
            return text

        except asyncio.TimeoutError:
            _log.warning(
                "Gemini Pro synthesis timed out (%.0fs). session_id=%s",
                _PRO_SYNTHESIS_TIMEOUT,
                snapshot.session_id,
            )
            return None

        except Exception as exc:
            # Catches: ResourceExhausted, StopCandidateException, ServiceUnavailable, etc.
            _log.warning(
                "Gemini Pro synthesis failed: %s. session_id=%s",
                exc,
                snapshot.session_id,
            )
            return None
